server:
  port: 8080
  maxPostSize: -1
  maxHttpHeaderSize: 102400



spring:
    datasource:
        name: oracle
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat,wall,log4j2  #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          driver-class-name: oracle.jdbc.OracleDriver
          #基本属性
          url: jdbc:oracle:thin:@192.168.1.23:1521:orcl
          username: province
          password: genesys
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true #是否在连接空闲一段时间后检测其可用性
          test-on-borrow: false #是否在获得连接后检测其可用性
          test-on-return: false #是否在连接放回连接池后检测其可用性
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: true #打开PSCache，并且指定每个连接上PSCache的大小
          max-pool-prepared-statement-per-connection-size: 20
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.province.receive.domain  # 注意：对应实体类的路径

es:
   host: 192.168.1.23